### ISSUE TITLE
mustache 0.6 breaks file paths with multiple extensions

### ISSUE THREAD

**Issue by tynopex** [nickel-org/rust-mustache#13]
Calling `mustache::compile_path(Path::new("foo.bar.mustache"))` will instead try to open `"foo.mustache"`.

This is due to the updates to `mustache::compile_path` interfering with the use of `set_extension` in `mustache::Context::compile_path`

**Comment by Ryman** [comment]
Well that's embarassing :tired_face: Will fix this very soon!

**Comment by Ryman** [comment]
Published 0.6.1
