### ISSUE TITLE
Fails to render with data that contains Option<String>

### ISSUE THREAD

**Issue by cburgdorf** [nickel-org/rust-mustache#20]
It seems template fail to render entirely if they contain `Option<String>` even so if that particular property isn't even used in the template. What's the reasoning behind that?

It fails with:

`Error: Problem rendering template: "unsupported type"`

/cc @Ryman

**Comment by Ryman** [comment]
It looks like it fails when encoding, do you have an example of the template, data and expected behavior?

**Comment by cburgdorf** [comment]
Sorry this took me so long. Checkout [this](https://github.com/nickel-org/rust-mustache/tree/bug-repro) it shows the bug when you run it.
