### ISSUE TITLE
how to use loop

### ISSUE THREAD

**Issue by nyrf** [nickel-org/rust-mustache#24]
like 

```rust
let mut users: Vec<User> = ver![];
users.push(user1);
users.push(user2);
let mut data = HashMap::<&str, _>::new();
data.insert("users", users);
return res.render("views/posts.tpl",&data);
```

```html
{{#users}}
  {{name}}
{{/users}}
```

**Comment by Ryman** [comment]
Does https://github.com/nickel-org/rust-mustache/pull/25 provide what you need? (The code you've pasted basically works, so I'm not sure?)

**Comment by nyrf** [comment]
@Ryman Sorry, my mistake, i forgot add `#[derive(RustcEncodable)]` for struct, thanks.

**Comment by nyrf** [comment]
@Ryman BTW,  when use vet!, it can't use other type. eg:

```rust
let mut users: Vec<User> = ver![];
users.push(user1); 
users.push(user2);
let title = "users list";
let mut data = HashMap::new();
data.insert("users", &users);
data.insert("title", &title);
return res.render("views/posts.tpl",&data);
```
got error:  `error: mismatched types:`

**Comment by nyrf** [comment]
I found use to_json can make it work.

```rust
data.insert("users".to_owned(), users.to_json());
data.insert("title".to_owned(), title.to_json());
```

**Comment by nyrf** [comment]
@Ryman BTW, how to add helpers,is it posible?

**Comment by Ryman** [comment]
> got error: error: mismatched types:

This is because you're adding 2 different types to a HashMap (without resorting to trait objects), you should instead try:

```rust
let mut users: Vec<User> = vec![];
users.push(user1); 
users.push(user2);

let title = "users list";

#[derive(RustcEncodable)]
struct ViewModel {
    title: String,
    users: Vec<User>,
}

let data = ViewModel {
    users: users,
    title: title.into()
};

return res.render("views/posts.tpl", &data);
```

> BTW, how to add helpers,is it posible?

I'm not sure exactly what you mean, can you give an example?

**Comment by nyrf** [comment]
Thanks, I means that like this:

```
{
  "name": "Willy",
  "wrapped": function() {
    return function(text, render) {
      return "<b>" + render(text) + "</b>"
    }
  }
}
```
The wrapped is a function.

**Comment by Ryman** [comment]
@nyrf I think [this is what you're looking for](http://nickel.rs/rust-mustache/mustache/builder/struct.MapBuilder.html#method.insert_fn)! :8ball:

**Comment by nyrf** [comment]
@Ryman Thanks, i've tried this, but it not work with nickel, got error `error: the trait `rustc_serialize::serialize::Encodable` is not implemented for the type `mustache::Data` [E0277]`, and it seems not work with 

```
let mut users: Vec<User> = vec![];
users.push(user1); 
users.push(user2);

let title = "users list";

#[derive(RustcEncodable)]
struct ViewModel {
    title: String,
    users: Vec<User>,
}

let data = ViewModel {
    users: users,
    title: title.into()
};

return res.render("views/posts.tpl", &data);
```

**Comment by Ryman** [comment]
Please take a look at https://github.com/nickel-org/nickel.rs/pull/287

**Comment by nyrf** [comment]
Thanks.
