### ISSUE TITLE
mustache::Template::render_data() should return an io::Result

### ISSUE THREAD

**Issue by iamcodemaker** [nickel-org/rust-mustache#29]
Currently, if rendering to the provided io::Write object fails, the program will panic. To avoid this, the user must render to a buffer (that shouldn't fail), then copy the buffer to a file (which might fail for various reasons). The render_data() method and associated methods in RenderContext should not call unwrap() and instead should bubble up io::Errors.

**Comment by Ryman** [comment]
@iamcodemaker I've opened #36 to address this, I'll leave the PR open a few days for comments.

cc @iamsebastian  @indiv0 (upvoters who may be interested)

**Comment by Ryman** [comment]
#36 is included in 0.8, so I'm closing this, please reopen if you want to discuss alternative changes!

**Comment by iamsebastian** [comment]
Thanks for highlighting, @Ryman
