### ISSUE TITLE
Support fmt::Write

### ISSUE THREAD

**Issue by SethDusek** [nickel-org/rust-mustache#31]
This would mean we can write directly to a String, which isn't possible with the io::Write trait since the bytes aren't guaranteed to be valid utf-8

**Comment by Ryman** [comment]
The docs for `fmt::Write` kind of suggest we shouldn't really consider it to exist (outside of libcore) so I'm uncertain about adding this. Perhaps a `render_to_string` method would get most of the benefit here?

**Comment by Ryman** [comment]
Closed via #43. Thanks for the suggestion.
