### ISSUE TITLE
Support Serde

### ISSUE THREAD

**Issue by KodrAus** [nickel-org/rust-mustache#33]
Needed for https://github.com/nickel-org/nickel.rs/issues/345

It'd be good to support `serde` in templates, it doesn't look like this crate has any serialisable structs of its own, so it shouldn't be necessary to add dependencies on `syntex`.

**Comment by Ryman** [comment]
I plan to implement this once https://github.com/nickel-org/rust-mustache/pull/36 lands.

**Comment by KodrAus** [comment]
Cool stuff, my `nickel` branch is just about ready to go once this goes through. Thanks!

**Comment by neoel** [comment]
I implemented something like this, not the best way to implement this though.

`
fn value_to_mustache(value: Value) -> Data {
    // Turns a serde_json::Value into mustache::Data

    return match value {
        Value::Null => Data::StrVal("".to_string()),
        Value::Bool(val) => Data::Bool(val),
        Value::I64(val) => Data::StrVal(val.to_string()),
        Value::U64(val) => Data::StrVal(val.to_string()),
        Value::F64(val) => Data::StrVal(val.to_string()),
        Value::String(val) => Data::StrVal(val.to_string()),
        Value::Array(vector) => {
            let mut _new = Vec::new();
            for item in vector.into_iter() {
                _new.push(value_to_mustache(item));
            }
            Data::VecVal(_new)
        },
        Value::Object(object) => {
            let mut _new = HashMap::new();
            for (key, val) in object.iter() {
                _new.insert(key.clone(), value_to_mustache(val.clone()));
            }
            Data::Map(_new)
        },
    }
}`

Works for me ;)

**Comment by viperscape** [comment]
Any status on this? I'm having an issue where I am using Serde_derive macro elsewhere and it seems to be giving me an issue with RustcEncodable

**Comment by jolhoeft** [comment]
We have a pull request (#52), but it appears to have some major API changes. I'm going to push the tip of master as 0.8.1, and we might make Serde support the beginning of the 0.9 train.

I'm not in a position to test the Serde support in #52, are you able to?

**Comment by Ryman** [comment]
Merged serde support in https://github.com/nickel-org/rust-mustache/pull/55! 🥂
