### ISSUE TITLE
Disable systematic HTML escapes

### ISSUE THREAD

**Issue by Giels** [nickel-org/rust-mustache#34]
rust-mustache should either offer an option to turn off (or on) HTML escapment, or simply not provide this capability.

- It prevents inserting pre-escaped HTML;
- It breaks < pre > blocks;
- Other template engines, such as maud and rustache, already offer this capability.

**Comment by Ryman** [comment]
`{{{<html>}}}` should be unescaped, it passes this [spec](https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L52-L58)?

**Comment by Giels** [comment]
You are correct. Sorry for the noise.
