### ISSUE TITLE
Missing(?) spec tests (and compliance failure)

### ISSUE THREAD

**Issue by Giels** [nickel-org/rust-mustache#35]
It seems that rust-mustache is missing some spec compliance tests, such as triple-mustache and & interactions with the implicit iterator (see https://github.com/mustache/spec/issues/82). rust-mustache fails in this case, with, 'expect map: [""]'.

Additionally, mustache is supposed to look into parents whenever a missing variable is encountered, but rust-mustache does not seem to do so.
(From section Variables in mustache(5): "The most basic tag type is the variable. [...] If there is no name key, the parent contexts will be checked recursively. If the top context is reached and the name key is still not found, nothing will be rendered.").

Also see the specs compliance test for interpolation:
" 2) Walk the context stack from top to bottom, finding the first context
that is a) a hash containing the name as a key OR b) an object responding
to a method with the given name." (https://github.com/mustache/spec/blob/master/specs/interpolation.yml)

Also, "If the top context is reached and the name key is still not found, nothing will be rendered." should mean that the current behavior for rust-mustache is incorrect since it errors out instead of rendering an empty string when the context is changed by the beginning of a section.

Example failure cases:

```
<html>
<body>
{{#payload.list}}
{{{.}}}
{{/payloadlist}}

{{#payload.list}}
{{&.}}
{{/payload.list}}

{{#payload.list}}
{{payload.test}}
{{/payload.list}}

{{#payload.list}}
{{test}}
{{/payload.list}}
</body>
</html>
```

With data equivalent to something like the following:

```
payload: { list: { "<p>hello</p>", "<p>world</p>" }, test: "hello world" }
```

**Comment by Ryman** [comment]
This seems to be two separate issues logged as one? The spec really does seem to be missing a lot of cases :(

**Comment by Ryman** [comment]
Opened #39 as a fix for this.
