### ISSUE TITLE
Push 0.8.1 to crates.io

### ISSUE THREAD

**Issue by jolhoeft** [nickel-org/rust-mustache#51]
Do the recent changes merit creating a 0.8.1 version? The most recent commit would help with some bugs we have.

**Comment by jolhoeft** [comment]
Unless there are objections, I am going to push the tip of head as 0.8.1.

**Comment by jolhoeft** [comment]
Pushed to crates.io

**Comment by Ryman** [comment]
@jolhoeft Thanks for taking initiative here, sorry for the radio silence.

**Comment by jolhoeft** [comment]
No problem, glad to see you back.
