### ISSUE TITLE
push tags for releases

### ISSUE THREAD

**Issue by cardoe** [nickel-org/rust-mustache#54]
When you do a release to crates.io please push a tag for the corresponding revision to git. You can use `cargo-release` to handle this for you automatically.

**Comment by Ryman** [comment]
Hi, thanks for the issue!

I've pushed up the tags for the last few releases and added [some notes](https://github.com/nickel-org/rust-mustache/commit/3cf21db15d09abfdb48c5e0e52abd69f4ec35a55) to the readme for maintainer reference. I'll look into using something like cargo-release in future :)
